CREATE TABLE Role
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE Client
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR NOT NULL UNIQUE,
    email VARCHAR NOT NULL UNIQUE,
    secret_key VARCHAR NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (role_id) REFERENCES Role (id) ON DELETE SET NULL
);

CREATE TABLE Currency
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR,
    minimal_amount NUMERIC(9, 8) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Wallet
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    client_id INT NOT NULL,
    currency_id INT NOT NULL,
    amount NUMERIC(18, 8) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (client_id) REFERENCES Client(id) ON DELETE CASCADE,
    FOREIGN KEY (currency_id) REFERENCES Currency(id) ON DELETE SET NULL
);

CREATE TABLE Rate
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    currency_to INT,
    currency_from INT,
    cost NUMERIC(60, 50) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (currency_to) REFERENCES Currency(id) ON DELETE SET NULL,
    FOREIGN KEY (currency_from) REFERENCES Currency(id) ON DELETE SET NULL
);

CREATE TABLE Operation
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE Operation_history
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    operation_id INT NOT NULL,
    client_id INT NOT NULL,
    currency_id INT NOT NULL,
    amount NUMERIC(18, 8) NOT NULL,
    date DATE NOT NULL,
    transfer_currency_id INT,
    transfer_wallet VARCHAR,
    PRIMARY KEY (id),
    FOREIGN KEY (operation_id) REFERENCES Operation(id),
    FOREIGN KEY (client_id) REFERENCES Client(id),
    FOREIGN KEY (currency_id) REFERENCES Currency(id),
    FOREIGN KEY (transfer_currency_id) REFERENCES Currency(id)
);

INSERT INTO Role (title)
VALUES
    ('ADMIN'),
    ('USER'),
    ('INACTIVE_USER');

INSERT INTO Client(username, email, secret_key, role_id)
VALUES
    ('admin', 'admin@email.ru', '$2a$10$lJAmmAuaM2Yk8H8thTc.OuKdZJDgf8dIBuFe/uukZicuLgrmMY5xS', 1);

INSERT INTO Currency (title, minimal_amount)
VALUES
    ('BTC', 0.00000001),
    ('TON', 0.01),
    ('RUB', 0.01);

INSERT INTO Rate (currency_to, currency_from, cost)
VALUES
    (1, 2, 1490760.51),
    (1, 3, 1750823.19),
    (2, 1, 0.00000067),
    (2, 3, 1.20),
    (3, 1, 0.00000057),
    (3, 2, 0.83);

INSERT INTO Operation(title)
VALUES
    ('Пополнение'),
    ('Вывод'),
    ('Обмен');

/*DROP TABLE Operation_history;
DROP TABLE Operation;
DROP TABLE Rate;
DROP TABLE Wallet;
DROP TABLE Currency;
DROP TABLE Client;
DROP TABLE Role;*/